### ISSUE TITLE
vote counts / probabilities for classification forest

### ISSUE THREAD

**Issue by rmflight** [mnwright/ranger#18]
As an alternative to just returning the majority vote when predicting from a classification forest, could the number of votes for each class be returned, alternatively normalized by the number of trees?

I think this would be equivalent to the `prob` and `votes` types in `randomForest::predict.randomForest`.

**Comment by LluisRamon** [comment]
It would be a nice enhancement!

**Comment by mnwright** [comment]
Is there any advantage compared to just using "probability = TRUE" when growing the trees? That approach should perform better for probability estimation, see Malley et al. (2012). 

Malley, J.D. et al. (2012). Probability machines: consistent probability estimation using nonparametric learning machines. Methods Inf Med, 51(1), 74.

**Comment by rmflight** [comment]
I'm not sure that this is an advantage or not to using "probability=TRUE". I will take a look at Malley (2012), and get back to you.

**Comment by mnwright** [comment]
Option to obtain tree-wise results added. For probabilities I would still prefer probability forests and added no additional aggregator.

**Comment by rmflight** [comment]
Thanks @mnwright! Will definitely investigate the probability forest option more as well.
