### ISSUE TITLE
Importance calculation takes too much memory and time

### ISSUE THREAD

**Issue by mbq** [mnwright/ranger#2]
Computing importance (all kinds) in ranger involves first creating a numTrees x numFeatures matrix (made of `variable_importance` vectors in each tree object), and then averaging it by row, which has a substantial impact on memory use and speed for large numTrees; ranger should just accumulate those values in place, thus using at most numFeatures x numThreads memory.

**Comment by mnwright** [comment]
Done. Thanks.

**Comment by mbq** [comment]
Great, thanks.
