### ISSUE TITLE
PDF and sample size

### ISSUE THREAD

**Issue by PhilippPro** [mnwright/ranger#27]
Hi Marvin,

nice package. I have two suggestions:
1. In the description pdf (https://cran.r-project.org/web/packages/ranger/ranger.pdf) in the "ranger" section the "values" are too long and are bigger than the page size. 
2. I wanted to specify the sample size of the trees, but I could not find an option for that in the function ranger.

Cheers,
Philipp

**Comment by mnwright** [comment]
1) Fixed, thanks
2) Do you mean the minimal number of samples in the terminal nodes? This would be min.node.size.

**Comment by PhilippPro** [comment]
2) No I mean the number of samples used in each tree. (chosen with Bootstrap or Subsampling)

**Comment by mnwright** [comment]
Unfortunately that's not implemented yet. But It's no big deal, I will add it soon.

**Comment by mnwright** [comment]
Done.
