### ISSUE TITLE
Transpose 'classification.table' and rename to 'confusion.matrix' 

### ISSUE THREAD

**Issue by mnwright** [mnwright/ranger#4]
In other packages and in general, the confusion matrix is transposed, compared to ranger. We should therefore transpose it. The standard name is 'confusion.matrix' instead of 'classification.table', so it should be renamed.

Thanks to Winston Peak.

**Comment by stefanherzog** [comment]
Sounds good!

Maybe it would be convenient to use **caret**'s function [confusionMatrix](http://www.inside-r.org/node/86995) as an inspiration (or suggest it as the default way to construct a confusion matrix).

**Comment by mnwright** [comment]
Done.
