### ISSUE TITLE
Allow the user to abort calculation

### ISSUE THREAD

**Issue by mllg** [mnwright/ranger#5]
This is pretty simple, you just need to call the Rcpp function `checkUserInterrupt()` every now and then. See Section 2.4 of <http://dirk.eddelbuettel.com/code/rcpp/Rcpp-attributes.pdf>.

**Comment by mnwright** [comment]
Tried (branch allow_interrupt). But if multithreading is used, the whole R session is killed on the interrupt.

Any idea?

**Comment by mbq** [comment]
You can do this only in a serial version; IMHO there is no documented way of *just* checking for interrupt (i.e. without immediate return to R in case it was triggered) so that it can be used to gracefully terminate a bundle of threads.

**Comment by mnwright** [comment]
Thanks. This is a must-have features, so I'll keep this open.

**Comment by mllg** [comment]
RcppProgress might be helpful: http://gallery.rcpp.org/articles/using-rcppprogress/

**Comment by mnwright** [comment]
RcppProgress didn't work out of the box for C++11 threads. However, I used a similar approach and it seems to work now.
